source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use sqlite3 as the database for Active Record in development
group :development, :test do
  gem 'sqlite3'
end
# Use sqlite3 as the database for Active Record in production
group :production do
  gem 'pg'
end
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Use Devise to provide authentication modules
gem 'devise'

# Interface serialization
gem 'active_model_serializers', '~> 0.10.0'

# Multi-tenant
gem 'apartment'

# Permission library
gem 'cancan'

# Batch api
gem 'batch_api', '~> 0.3.0'

# Provide for Heroku
gem 'rails_12factor', group: :production

# jQuery Datatables Server side plugin
gem 'ajax-datatables-rails'

# Ruby Http Client
gem 'http'

# Bot framework Connector API Client
gem 'bot_connector_api', :git => 'https://github.com/codemeow5/RubyConnectorClient.git'

# Bot framework State REST API Client
gem 'bot_state_api', :git => 'https://github.com/codemeow5/RubyStateClient.git'

# Sidekiq background job queue
gem 'sidekiq'

# Official Support for Sidekiq with the Apartment gem
gem 'apartment-sidekiq'

# Support for Heroku Redis To Go  
gem 'redis'

# Support RFC4122 V1 UUID
gem 'uuid', '~> 2.3', '>= 2.3.8'

# HttpPack Server-Side Plugin
gem 'http_pack', :git => 'https://github.com/codemeow5/ruby-httppack.git'

